import {validateProject, safePage, progressOf} from './model.js';
const $=s=>document.querySelector(s), labels={R:'Ready',I:'In process',P:'Pending',N:'No aplica'};
let guide,project,baseline,key,draft,dirty=false,opened=new Set(),expanded=new Set(),views=new Map(),filters=new Set(),query='';
const el=(tag,props={},text)=>{const node=document.createElement(tag);Object.assign(node,props);if(text!==undefined)node.textContent=text;return node;};
function report(message){$('#error').textContent=message;$('#error').hidden=false;}
function edited(){dirty=JSON.stringify(project)!==baseline;try{sessionStorage.setItem(key,JSON.stringify({baseline,project}));}catch{$('#save-status').textContent='No se puede conservar el borrador en este navegador. Exporta antes de salir.';return;}$('#save-status').textContent=dirty?'Borrador de sesión · cambios pendientes de integrar en el repositorio.':'Configuración igual al archivo cargado del repositorio.';}
function stats(){const counts={R:0,I:0,P:0,N:0};Object.values(project.sections).forEach(s=>counts[s.status]++);for(const s of Object.keys(labels))$(`[data-status="${s}"] span`).textContent=counts[s];const p=progressOf(project);$('#percent').textContent=p.percent===null?'—':`${p.percent}%`;$('#progress').value=p.percent||0;$('#progress-label').textContent=p.applicable?`${p.ready} de ${p.applicable} secciones listas`:'Sin secciones aplicables';$('#project-title').textContent=project.name;document.title=`${project.name} · DS Workspace`;}
function field(title,value,update,type='input'){const l=el('label',{},title), input=el(type,{value});input.addEventListener('change',()=>update(input.value));l.append(input);return l;}
function render(){stats();const matrix=$('#matrix');matrix.replaceChildren();let count=0;
for(const c of guide.categories){const items=c.items.filter(i=>(!filters.size||filters.has(project.sections[i.id].status))&&`${i.number} ${i.title} ${i.define} ${c.title}`.toLocaleLowerCase('es').includes(query));if(!items.length)continue;count+=items.length;
const cat=el('details',{className:'category',open:expanded.has(c.id)||!!query||filters.size>0});cat.addEventListener('toggle',()=>{if(cat.open)expanded.add(c.id);else expanded.delete(c.id);});const summary=el('summary');summary.append(el('span',{className:'category-num'},c.number.padStart(2,'0')),el('span',{className:'category-title'},c.title));const totals=el('span',{className:'counts'});for(const s of Object.keys(labels)){const n=c.items.filter(i=>project.sections[i.id].status===s).length;totals.append(el('span',{title:labels[s]},`${n} ${s}`));}summary.append(totals);cat.append(summary,el('p',{className:'cat-intro'},c.objective));
for(const i of items){const p=project.sections[i.id],wrap=el('div',{className:'item'}),row=el('div',{className:'item-row'}),button=el('button',{className:'item-open'});button.setAttribute('aria-expanded',String(opened.has(i.id)));button.setAttribute('aria-controls',`panel-${i.id}`);button.append(el('span',{className:'item-number'},i.number),el('span',{className:'item-title'},i.title));
const panel=el('div',{className:'item-content',id:`panel-${i.id}`,hidden:!opened.has(i.id)});button.onclick=()=>{const open=panel.hidden;panel.hidden=!open;button.setAttribute('aria-expanded',String(open));open?opened.add(i.id):opened.delete(i.id);if(open&&!panel.childNodes.length)content(i,p,panel);};
const select=el('select',{className:'status-select'});select.dataset.value=p.status;select.setAttribute('aria-label',`Estado de ${i.title}`);for(const [s,l]of Object.entries(labels))select.append(el('option',{value:s},`${s} · ${l}`));select.value=p.status;select.onchange=()=>{const v=select.value;if(v==='R'&&(!p.review.by.trim()||!p.review.date||!p.review.evidence.trim())){report('Para marcar Ready, abre la sección y registra quién la revisó, la fecha y la evidencia.');select.value=p.status;return;}if(v==='N'&&!p.exclusionReason.trim()){report('Para marcar No aplica, abre la sección y registra el motivo de exclusión.');select.value=p.status;return;}$('#error').hidden=true;p.status=v;edited();render();const target=[...document.querySelectorAll('.status-select')].find(n=>n.getAttribute('aria-label')===`Estado de ${i.title}`);(target||$(`[data-status="${v}"]`)).focus();};row.append(button,select);wrap.append(row,panel);cat.append(wrap);if(!panel.hidden)content(i,p,panel);}
matrix.append(cat);}
$('#result-count').textContent=`${count} de ${Object.keys(project.sections).length} subsecciones`;if(!count)matrix.append(el('p',{className:'no-results'},'No hay secciones con estos filtros. Prueba otro estado o búsqueda.'));}
function content(i,p,panel){panel.replaceChildren();const bar=el('div',{className:'view-bar'}),toggle=el('label',{className:'switch'}),check=el('input',{type:'checkbox',checked:views.get(i.id)!==false});check.setAttribute('role','switch');toggle.append(check,document.createTextNode('Mostrar guía'));const mode=el('span',{},check.checked?'Guía':'Desarrollo');bar.append(toggle,mode,el('code',{},i.id));panel.append(bar);const body=el('div');panel.append(body);
const paint=()=>{body.replaceChildren();mode.textContent=check.checked?'Guía':'Desarrollo';if(check.checked){body.className='guide-grid';for(const [title,value]of [['Objetivo',i.objective],['Qué definir',i.define],['Accesibilidad',i.accessibility],['Entregable esperado',i.deliverable]]){const box=el('div');box.append(el('h3',{},title),el('p',{},value));body.append(box);}const box=el('div',{className:'wide'}),ul=el('ul');box.append(el('h3',{},'Criterios de aceptación'));for(const t of i.acceptance)ul.append(el('li',{},t));box.append(ul);body.append(box);}else{body.className='development';if(!p.page){const empty=el('div',{className:'empty'});empty.append(el('h3',{},'Esta sección todavía no tiene página'),el('p',{},'Desarróllala en Claude Design y utiliza esta ruta al integrarla:'),el('code',{},i.suggestedPath));body.append(empty);}else{const a=el('a',{href:p.page,target:'_blank',rel:'noopener noreferrer'},'Abrir página en otra pestaña ↗');body.append(a,el('small',{},'Si la página impide su carga dentro del contenedor o requiere iniciar sesión, utiliza el enlace.'),el('iframe',{src:p.page,title:`Desarrollo de ${i.title}`,loading:'lazy',referrerPolicy:'no-referrer'}));body.lastChild.setAttribute('sandbox','allow-scripts');}}};check.onchange=()=>{views.set(i.id,check.checked);paint();};paint();
const meta=el('div',{className:'metadata'});meta.append(field('Página de desarrollo · ruta relativa o URL HTTPS',p.page,v=>{if(v&&!safePage(v)){report('Usa una ruta sections/…html sin ../ o una URL HTTPS.');return;}p.page=v;edited();paint();}),field('Responsable',p.owner,v=>{p.owner=v;edited();}));meta.firstChild.append(el('small',{},`Destino sugerido: ${i.suggestedPath}`));meta.append(field('Decisiones y pendientes',p.notes,v=>{p.notes=v;edited();},'textarea'),field('Motivo de exclusión · necesario para N',p.exclusionReason,v=>{if(p.status==='N'&&!v.trim()){report('Mantén el motivo mientras el estado sea N.');render();return;}p.exclusionReason=v;edited();},'textarea'));
for(const [title,k]of [['Revisión · nombre','by'],['Revisión · fecha (AAAA-MM-DD)','date'],['Revisión · evidencia, criterios comprobados y enlaces','evidence']]){const f=field(title,p.review[k],v=>{if((p.status==='R'&&!v.trim())||(k==='date'&&v&&!/^\d{4}-\d{2}-\d{2}$/.test(v))){report('Ready necesita una revisión completa. Usa una fecha AAAA-MM-DD.');render();return;}p.review[k]=v;edited();},k==='evidence'?'textarea':'input');if(k==='date')f.lastChild.type='date';if(k==='evidence')f.className='wide';meta.append(f);}panel.append(meta);}
async function init(){try{const results=await Promise.all(['guide','project'].map(async n=>{const r=await fetch(`data/${n}.json`,{cache:'no-store'});if(!r.ok)throw Error(`No se pudo leer ${n}.json`);return r.json();}));[guide,project]=results;validateProject(project,guide);baseline=JSON.stringify(project);key=`ds-workspace:${project.projectId}:${location.pathname}`;try{draft=JSON.parse(sessionStorage.getItem(key));}catch{}if(draft&&JSON.stringify(draft.project)!==baseline){$('#draft-banner').hidden=false;if(draft.baseline!==baseline){$('#draft-banner').firstChild.textContent='El repositorio cambió desde el borrador. Recupéralo solo si quieres sustituir la configuración en pantalla; revisa el diff al integrarlo. ';}}
$('#project-name').value=project.name;$('#save-status').textContent='Configuración cargada del repositorio · los cambios se conservan como borrador de sesión.';render();}catch(e){report(`${e.message}. Inicia el servidor local indicado en README.md; abrir index.html con file:// no carga los JSON.`);}}
$('#search').oninput=e=>{query=e.target.value.trim().toLocaleLowerCase('es');render();};$('#filters').onclick=e=>{const b=e.target.closest('button');if(!b)return;const s=b.dataset.status;if(s==='all')filters.clear();else filters.has(s)?filters.delete(s):filters.add(s);for(const n of $('#filters').querySelectorAll('button'))n.setAttribute('aria-pressed',String(n.dataset.status==='all'?!filters.size:filters.has(n.dataset.status)));render();};$('#project-name').onchange=e=>{if(!project)return;project.name=e.target.value.trim()||'Mi Design System';e.target.value=project.name;edited();stats();};$('#expand').onclick=()=>{for(const c of guide.categories)expanded.add(c.id);render();};$('#collapse').onclick=()=>{expanded.clear();opened.clear();document.querySelectorAll('.category').forEach(n=>n.open=false);document.querySelectorAll('.item-content').forEach(n=>n.hidden=true);document.querySelectorAll('.item-open').forEach(n=>n.setAttribute('aria-expanded','false'));};
$('#export').onclick=()=>{if(!project)return;try{validateProject(project,guide);}catch(e){report(e.message);return;}const blob=new Blob([JSON.stringify(project,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a',{href:url,download:'project.json'});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#save-status').textContent='Configuración exportada · entrega project.json y las páginas modificadas a Claude Code. La integración en Git sigue pendiente.';};
$('#import').onclick=()=>$('#file').click();$('#file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2e6)throw Error('La configuración supera 2 MB');const next=JSON.parse(await f.text());validateProject(next,guide);if(dirty&&!confirm('Hay cambios de sesión. ¿Sustituirlos por el archivo importado?'))return;if(next.projectId!==project.projectId&&!confirm('El archivo pertenece a otro proyecto. ¿Cargarlo en esta plantilla?'))return;project=next;key=`ds-workspace:${project.projectId}:${location.pathname}`;$('#project-name').value=project.name;$('#draft-banner').hidden=true;$('#error').hidden=true;edited();render();}catch(err){report(`No se importó: ${err.message}`);}e.target.value='';};
$('#restore').onclick=()=>{try{validateProject(draft.project,guide);project=draft.project;$('#project-name').value=project.name;$('#draft-banner').hidden=true;edited();render();}catch(e){report(`Borrador incompatible: ${e.message}`);}};$('#discard').onclick=()=>{try{sessionStorage.removeItem(key);}catch{}$('#draft-banner').hidden=true;};window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});init();
