import {validateProject, progressOf, pagePath} from './model.js';
const $=s=>document.querySelector(s), labels={R:'Ready',I:'In process',P:'Pending',N:'No aplica'};
let guide,project,opened=new Set(),expanded=new Set(),views=new Map(),filters=new Set(),query='',found=new Map();
const el=(tag,props={},text)=>{const node=document.createElement(tag);Object.assign(node,props);if(text!==undefined)node.textContent=text;return node;};
function report(message){$('#error').textContent=message;$('#error').hidden=false;}
function stats(){const counts={R:0,I:0,P:0,N:0};Object.values(project.sections).forEach(s=>counts[s.status]++);for(const s of Object.keys(labels))$(`[data-status="${s}"] span`).textContent=counts[s];const p=progressOf(project);$('#percent').textContent=p.percent===null?'—':`${p.percent}%`;$('#progress').value=p.percent||0;$('#progress-label').textContent=p.applicable?`${p.ready} de ${p.applicable} secciones listas`:'Sin secciones aplicables';$('#project-title').textContent=project.name;document.title=`${project.name} · DS Workspace`;}
function pageExists(path){if(!found.has(path))found.set(path,fetch(path,{method:'HEAD',cache:'no-store'}).then(r=>r.ok&&/text\/html/i.test(r.headers.get('content-type')||'')).catch(()=>false));return found.get(path);}
function render(){stats();const matrix=$('#matrix');matrix.replaceChildren();let count=0;
for(const c of guide.categories){const items=c.items.filter(i=>(!filters.size||filters.has(project.sections[i.id].status))&&`${i.number} ${i.title} ${i.define} ${c.title}`.toLocaleLowerCase('es').includes(query));if(!items.length)continue;count+=items.length;
const cat=el('details',{className:'category',open:expanded.has(c.id)||!!query||filters.size>0});cat.addEventListener('toggle',()=>{if(cat.open)expanded.add(c.id);else expanded.delete(c.id);});const summary=el('summary');summary.append(el('span',{className:'category-num'},c.number.padStart(2,'0')),el('span',{className:'category-title'},c.title));const totals=el('span',{className:'counts'});for(const s of Object.keys(labels)){const n=c.items.filter(i=>project.sections[i.id].status===s).length;totals.append(el('span',{title:labels[s]},`${n} ${s}`));}summary.append(totals);cat.append(summary,el('p',{className:'cat-intro'},c.objective));
for(const i of items){const p=project.sections[i.id],wrap=el('div',{className:'item'}),row=el('div',{className:'item-row'}),button=el('button',{className:'item-open'});button.setAttribute('aria-expanded',String(opened.has(i.id)));button.setAttribute('aria-controls',`panel-${i.id}`);button.append(el('span',{className:'item-number'},i.number),el('span',{className:'item-title'},i.title));
const panel=el('div',{className:'item-content',id:`panel-${i.id}`,hidden:!opened.has(i.id)});button.onclick=()=>{const open=panel.hidden;panel.hidden=!open;button.setAttribute('aria-expanded',String(open));open?opened.add(i.id):opened.delete(i.id);if(open&&!panel.childNodes.length)content(i,p,panel);};
const tag=el('span',{className:'status-tag'},`${p.status} · ${labels[p.status]}`);tag.dataset.value=p.status;row.append(button,tag);wrap.append(row,panel);cat.append(wrap);if(!panel.hidden)content(i,p,panel);}
matrix.append(cat);}
$('#result-count').textContent=`${count} de ${Object.keys(project.sections).length} subsecciones`;if(!count)matrix.append(el('p',{className:'no-results'},'No hay secciones con estos filtros. Prueba otro estado o búsqueda.'));}
function frame(i,path,body){body.replaceChildren(el('a',{href:path,target:'_blank',rel:'noopener noreferrer'},'Abrir página en otra pestaña ↗'),el('small',{},'Si la página impide su carga dentro del contenedor o requiere iniciar sesión, utiliza el enlace.'));const f=el('iframe',{src:path,title:`Desarrollo de ${i.title}`,loading:'lazy',referrerPolicy:'no-referrer'});f.setAttribute('sandbox','allow-scripts');body.append(f);}
function noPage(i,body){const empty=el('div',{className:'empty'});empty.append(el('h3',{},'Sin página'),el('p',{},'Esta sección todavía no tiene página en la ruta prevista:'),el('code',{},i.suggestedPath));body.replaceChildren(empty);}
function develop(i,p,body){body.className='development';const path=pagePath(i,p);if(p.page){frame(i,path,body);return;}body.replaceChildren(el('p',{},'Comprobando si existe la página…'));pageExists(path).then(ok=>{if(body.isConnected)ok?frame(i,path,body):noPage(i,body);});}
function record(title,value,wide){const box=el('div',wide?{className:'wide'}:{});box.append(el('h3',{},title),el('p',{className:value?'':'muted'},value||'Sin registrar'));return box;}
function content(i,p,panel){panel.replaceChildren();const bar=el('div',{className:'view-bar'}),toggle=el('label',{className:'switch'}),check=el('input',{type:'checkbox',checked:views.get(i.id)!==false});check.setAttribute('role','switch');toggle.append(check,document.createTextNode('Mostrar guía'));const mode=el('span',{},check.checked?'Guía':'Desarrollo');bar.append(toggle,mode,el('code',{},i.id));panel.append(bar);const body=el('div');panel.append(body);
const paint=()=>{body.replaceChildren();mode.textContent=check.checked?'Guía':'Desarrollo';if(check.checked){body.className='guide-grid';for(const [title,value]of [['Objetivo',i.objective],['Qué definir',i.define],['Accesibilidad',i.accessibility],['Entregable esperado',i.deliverable]]){const box=el('div');box.append(el('h3',{},title),el('p',{},value));body.append(box);}const box=el('div',{className:'wide'}),ul=el('ul');box.append(el('h3',{},'Criterios de aceptación'));for(const t of i.acceptance)ul.append(el('li',{},t));box.append(ul);body.append(box);}else develop(i,p,body);};check.onchange=()=>{views.set(i.id,check.checked);paint();};paint();
const meta=el('div',{className:'metadata'});meta.append(record('Página',p.page||`${i.suggestedPath} (ruta sugerida)`),record('Responsable',p.owner),record('Decisiones y pendientes',p.notes,true));if(p.status==='N')meta.append(record('Motivo de exclusión',p.exclusionReason,true));meta.append(record('Revisión · nombre',p.review.by),record('Revisión · fecha',p.review.date),record('Revisión · evidencia',p.review.evidence,true));panel.append(meta);}
async function init(){try{const results=await Promise.all(['guide','project'].map(async n=>{const r=await fetch(`data/${n}.json`,{cache:'no-store'});if(!r.ok)throw Error(`No se pudo leer ${n}.json`);return r.json();}));[guide,project]=results;validateProject(project,guide);$('#save-status').textContent='Vista de solo lectura del estado del repositorio. Se edita en Claude Design.';render();}catch(e){report(`${e.message}. Inicia el servidor local indicado en README.md; abrir index.html con file:// no carga los JSON.`);}}
$('#search').oninput=e=>{query=e.target.value.trim().toLocaleLowerCase('es');render();};
$('#filters').onclick=e=>{const b=e.target.closest('button');if(!b)return;const s=b.dataset.status;if(s==='all')filters.clear();else filters.has(s)?filters.delete(s):filters.add(s);for(const n of $('#filters').querySelectorAll('button'))n.setAttribute('aria-pressed',String(n.dataset.status==='all'?!filters.size:filters.has(n.dataset.status)));render();};
$('#expand').onclick=()=>{for(const c of guide.categories)expanded.add(c.id);render();};
$('#collapse').onclick=()=>{expanded.clear();opened.clear();document.querySelectorAll('.category').forEach(n=>n.open=false);document.querySelectorAll('.item-content').forEach(n=>n.hidden=true);document.querySelectorAll('.item-open').forEach(n=>n.setAttribute('aria-expanded','false'));};
init();
