import {validateProject, progressOf, pageCandidates} from './model.js';
const $=s=>document.querySelector(s), labels={R:'Ready',I:'In process',P:'Pending',N:'No aplica'};
let guide,project,opened=new Set(),expanded=new Set(),menuOpen=new Set(),views=new Map(),filters=new Set(),query='',found=new Map();
const el=(tag,props={},text)=>{const node=document.createElement(tag);Object.assign(node,props);if(text!==undefined)node.textContent=text;return node;};
function report(message){$('#error').textContent=message;$('#error').hidden=false;}
function stats(){const counts={R:0,I:0,P:0,N:0};Object.values(project.sections).forEach(s=>counts[s.status]++);for(const s of Object.keys(labels))document.querySelectorAll(`[data-status="${s}"] span,[data-count="${s}"]`).forEach(n=>n.textContent=counts[s]);const p=progressOf(project);$('#result-count').textContent=`${p.ready}/${p.applicable}`;$('#progress').value=p.percent||0;$('#scope-progress').value=p.scope||0;$('#project-title').textContent=project.name;$('#mobile-title').textContent=`DSBook · ${project.name}`;$('#page-title').textContent=`DSBook · ${project.name}`;document.title=`DSBook · ${project.name}`;$('#footer-name').textContent=`DSBook · ${project.name}`;}
function syncFilters(){for(const n of $('#filters').querySelectorAll('button'))n.setAttribute('aria-pressed',String(n.dataset.status==='all'?!filters.size:filters.has(n.dataset.status)));document.querySelectorAll('[data-filter]').forEach(c=>{c.checked=c.dataset.filter==='all'?!filters.size:filters.has(c.dataset.filter);});}
function pageExists(path){if(!found.has(path))found.set(path,fetch(path,{method:'HEAD',cache:'no-store'}).then(r=>r.ok&&/text\/html/i.test(r.headers.get('content-type')||'')).catch(()=>false));return found.get(path);}
function visible(){return guide.categories.map(c=>({c,items:c.items.filter(i=>(!filters.size||filters.has(project.sections[i.id].status))&&`${i.number} ${i.title} ${i.define} ${c.title}`.toLocaleLowerCase('es').includes(query))})).filter(v=>v.items.length);}
function render(){stats();syncFilters();const matrix=$('#matrix'),view=visible();matrix.replaceChildren();let count=0;
for(const {c,items} of view){count+=items.length;
const cat=el('details',{className:'category',id:`cat-${c.id}`,open:expanded.has(c.id)||!!query||filters.size>0});cat.addEventListener('toggle',()=>{if(cat.open)expanded.add(c.id);else expanded.delete(c.id);});const summary=el('summary');summary.append(el('span',{className:'category-num'},c.number.padStart(2,'0')),el('span',{className:'category-title'},c.title));const totals=el('span',{className:'counts'});for(const s of Object.keys(labels)){const n=c.items.filter(i=>project.sections[i.id].status===s).length;totals.append(el('span',{title:labels[s]},`${n} ${s}`));}summary.append(totals);cat.append(summary,el('p',{className:'cat-intro'},c.objective));
for(const i of items){const p=project.sections[i.id],wrap=el('div',{className:'item',id:`item-${i.id}`}),row=el('div',{className:'item-row'}),button=el('button',{className:'item-open'});button.setAttribute('aria-expanded',String(opened.has(i.id)));button.setAttribute('aria-controls',`panel-${i.id}`);button.append(el('span',{className:'item-number'},i.number),el('span',{className:'item-title'},i.title));
const panel=el('div',{className:'item-content',id:`panel-${i.id}`,hidden:!opened.has(i.id)});button.onclick=()=>{const open=panel.hidden;panel.hidden=!open;button.setAttribute('aria-expanded',String(open));open?opened.add(i.id):opened.delete(i.id);if(open&&!panel.childNodes.length)content(i,p,panel);};
const tag=el('span',{className:'status-tag'},`${p.status} · ${labels[p.status]}`);tag.dataset.value=p.status;row.append(button,tag);wrap.append(row,panel);cat.append(wrap);if(!panel.hidden)content(i,p,panel);}
matrix.append(cat);}
if(!count)matrix.append(el('p',{className:'no-results'},'No hay secciones con estos filtros. Prueba otro estado o búsqueda.'));
renderMenu(view);}
function renderMenu(view){const menu=$('#menu'),top=menu.scrollTop,focusKey=document.activeElement&&menu.contains(document.activeElement)?document.activeElement.dataset.key:null,auto=!!query||filters.size>0;menu.replaceChildren();
for(const {c,items} of view){const open=auto||menuOpen.has(c.id),sec=el('div',{className:'menu-cat'}),row=el('div',{className:'menu-cat-row'});
const tog=el('button',{className:'menu-toggle',disabled:auto});tog.dataset.key=`t-${c.id}`;tog.setAttribute('aria-expanded',String(open));tog.setAttribute('aria-controls',`menu-${c.id}`);tog.setAttribute('aria-label',`${c.title}: ${open?'plegar':'desplegar'} subsecciones`);tog.onclick=()=>{open?menuOpen.delete(c.id):menuOpen.add(c.id);renderMenu(view);};
const link=el('a',{href:`#cat-${c.id}`,className:'menu-cat-link'});link.dataset.key=`c-${c.id}`;link.dataset.cat=c.id;link.append(el('span',{className:'menu-num'},c.number.padStart(2,'0')),el('span',{},c.title));link.onclick=e=>{e.preventDefault();goTo(c.id);};
row.append(tog,link);const list=el('ul',{className:'menu-items',id:`menu-${c.id}`,hidden:!open});
for(const i of items){const p=project.sections[i.id],li=el('li'),a=el('a',{href:`#item-${i.id}`,className:'menu-item'});a.dataset.key=`i-${i.id}`;a.dataset.item=i.id;a.append(el('span',{className:'menu-num'},i.number),el('span',{className:'menu-title'},i.title));const b=el('span',{className:'menu-status'},p.status);b.dataset.value=p.status;b.append(el('span',{className:'sr-only'},` · ${labels[p.status]}`));a.append(b);a.onclick=e=>{e.preventDefault();goTo(c.id,i.id);};li.append(a);list.append(li);}
sec.append(row,list);menu.append(sec);}
menu.scrollTop=top;if(focusKey)menu.querySelector(`[data-key="${CSS.escape(focusKey)}"]`)?.focus({preventScroll:true});markActive(true);}
function goTo(catId,itemId){expanded.add(catId);menuOpen.add(catId);if(itemId)opened.add(itemId);render();const t=document.getElementById(itemId?`item-${itemId}`:`cat-${catId}`);if(!t)return;t.scrollIntoView({block:'start'});(itemId?t.querySelector('.item-open'):t.querySelector('summary')).focus({preventScroll:true});history.replaceState(null,'',`#${t.id}`);setDrawer(false);closeFlyout();}
function markActive(force){const menu=$('#menu');let cur=null,curCat=null;for(const n of document.querySelectorAll('#matrix .category')){if(n.getBoundingClientRect().top<=140)curCat=n;else break;}for(const n of document.querySelectorAll('#matrix .item')){if(!n.closest('details').open)continue;if(n.getBoundingClientRect().top<=140)cur=n;else break;}
const itemId=cur&&curCat&&curCat.contains(cur)?cur.id.slice(5):null,catId=curCat?curCat.id.slice(4):null;
menu.querySelectorAll('[aria-current]').forEach(n=>n.removeAttribute('aria-current'));
const target=itemId?menu.querySelector(`[data-item="${CSS.escape(itemId)}"]`):catId?menu.querySelector(`[data-cat="${CSS.escape(catId)}"]`):null;if(!target)return;target.setAttribute('aria-current','location');
const key=itemId||catId;if(force||markActive.last!==key){markActive.last=key;if(target.offsetParent){const t=target.getBoundingClientRect(),m=menu.getBoundingClientRect();if(t.top<m.top+8||t.bottom>m.bottom-8)menu.scrollTop+=t.top-m.top-m.height/3;}}}
let ticking=false;window.addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{ticking=false;if(project)markActive(false);});},{passive:true});
function setDrawer(open){$('#sidebar').classList.toggle('open',open);$('#menu-button').setAttribute('aria-expanded',String(open));document.body.classList.toggle('drawer-open',open);}
$('#menu-button').onclick=()=>setDrawer(!$('#sidebar').classList.contains('open'));$('#scrim').onclick=()=>setDrawer(false);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#sidebar').classList.contains('open')){setDrawer(false);$('#menu-button').focus();}});
function frame(i,path,body){body.replaceChildren(el('a',{href:path,target:'_blank',rel:'noopener noreferrer'},'Abrir página en otra pestaña ↗'),el('small',{},'Si la página impide su carga dentro del contenedor o requiere iniciar sesión, utiliza el enlace.'));const f=el('iframe',{src:path,title:`Desarrollo de ${i.title}`,loading:'lazy',referrerPolicy:'no-referrer'});f.setAttribute('sandbox','allow-scripts');body.append(f);}
function noPage(i,body){const empty=el('div',{className:'empty'});empty.append(el('h3',{},'Sin página'),el('p',{},'Esta sección todavía no tiene página en la ruta prevista:'),el('code',{},i.suggestedPath));body.replaceChildren(empty);}
function develop(i,p,body){body.className='development';const [first,...rest]=pageCandidates(i,p);if(p.page){frame(i,first,body);return;}body.replaceChildren(el('p',{},'Comprobando si existe la página…'));Promise.all([first,...rest].map(pageExists)).then(r=>{const k=r.indexOf(true);if(body.isConnected)k>=0?frame(i,[first,...rest][k],body):noPage(i,body);});}
function record(title,value,wide){const box=el('div',wide?{className:'wide'}:{});box.append(el('h3',{},title),el('p',{className:value?'':'muted'},value||'Sin registrar'));return box;}
function content(i,p,panel){panel.replaceChildren();const bar=el('div',{className:'view-bar'}),toggle=el('label',{className:'switch'}),check=el('input',{type:'checkbox',checked:views.get(i.id)!==false});check.setAttribute('role','switch');toggle.append(check,document.createTextNode('Mostrar guía'));const mode=el('span',{},check.checked?'Guía':'Desarrollo');bar.append(toggle,mode,el('code',{},i.id));panel.append(bar);const body=el('div');panel.append(body);
const paint=()=>{body.replaceChildren();mode.textContent=check.checked?'Guía':'Desarrollo';if(check.checked){body.className='guide-grid';for(const [title,value]of [['Objetivo',i.objective],['Qué definir',i.define],['Accesibilidad',i.accessibility],['Entregable esperado',i.deliverable]]){const box=el('div');box.append(el('h3',{},title),el('p',{},value));body.append(box);}const box=el('div',{className:'wide'}),ul=el('ul');box.append(el('h3',{},'Criterios de aceptación'));for(const t of i.acceptance)ul.append(el('li',{},t));box.append(ul);body.append(box);}else develop(i,p,body);};check.onchange=()=>{views.set(i.id,check.checked);paint();};paint();
const meta=el('div',{className:'metadata'});meta.append(record('Página',p.page||`${i.suggestedPath} (ruta sugerida)`),record('Responsable',p.owner),record('Decisiones y pendientes',p.notes,true));if(p.status==='N')meta.append(record('Motivo de exclusión',p.exclusionReason,true));meta.append(record('Revisión · nombre',p.review.by),record('Revisión · fecha',p.review.date),record('Revisión · evidencia',p.review.evidence,true));panel.append(meta);}
async function init(){try{const results=await Promise.all(['guide','project'].map(async n=>{const r=await fetch(`data/${n}.json`,{cache:'no-store'});if(!r.ok)throw Error(`No se pudo leer ${n}.json`);return r.json();}));[guide,project]=results;validateProject(project,guide);$('#save-status').textContent='Solo lectura · se edita en Claude Design';render();const h=decodeURIComponent(location.hash.slice(1));if(h.startsWith('item-')){const id=h.slice(5),c=guide.categories.find(c=>c.items.some(i=>i.id===id));if(c)goTo(c.id,id);}else if(h.startsWith('cat-')&&guide.categories.some(c=>c.id===h.slice(4)))goTo(h.slice(4));}catch(e){report(`${e.message}. Inicia el servidor local indicado en README.md; abrir index.html con file:// no carga los JSON.`);}}
const setQuery=v=>{query=v.trim().toLocaleLowerCase('es');for(const i of ['#search','#menu-search'])if($(i).value!==v)$(i).value=v;render();};
$('#search').oninput=e=>setQuery(e.target.value);$('#menu-search').oninput=e=>setQuery(e.target.value);
$('#filters').onclick=e=>{const b=e.target.closest('button');if(!b)return;const s=b.dataset.status;if(s==='all')filters.clear();else filters.has(s)?filters.delete(s):filters.add(s);render();};
$('#expand').onclick=()=>{for(const c of guide.categories){expanded.add(c.id);menuOpen.add(c.id);}render();};
$('#collapse').onclick=()=>{expanded.clear();opened.clear();menuOpen.clear();render();};
const shell=$('#shell'),side=$('#sidebar'),mobileMq=matchMedia('(max-width:950px)');
const panels={search:{btn:$('#search-btn'),el:$('#panel-search')},state:{btn:$('#state-btn'),el:$('#panel-state')},sections:{btn:$('#sections-btn'),el:$('#menu-wrap')}};
let pinned=null,hover=null,leaveTimer=null;
const isCollapsed=()=>shell.classList.contains('collapsed');
function current(){if(!isCollapsed())return null;if(pinned)return pinned;if(hover)return hover;return Object.keys(panels).find(k=>panels[k].el.contains(document.activeElement))||null;}
function applyFlyout(){const c=current();side.classList.toggle('flyout',!!c);side.dataset.panel=c||'';for(const k in panels)panels[k].btn.setAttribute('aria-expanded',String(k===c));}
function closeFlyout(){pinned=null;hover=null;clearTimeout(leaveTimer);applyFlyout();}
function brandLabel(){const b=$('#collapse-btn'),c=isCollapsed()&&!mobileMq.matches,t=mobileMq.matches?'Cerrar menú':c?'Expandir barra lateral':'Comprimir barra lateral';b.setAttribute('aria-expanded',String(!c));b.setAttribute('aria-label',`DSBook: ${t.toLowerCase()}`);b.title=t;}
function setCollapsed(c){shell.classList.toggle('collapsed',c);brandLabel();closeFlyout();}
$('#collapse-btn').onclick=()=>{if(mobileMq.matches)setDrawer(false);else setCollapsed(!isCollapsed());};mobileMq.addEventListener('change',brandLabel);
for(const [k,{btn,el:pel}] of Object.entries(panels)){
btn.onclick=()=>{if(pinned===k)closeFlyout();else{pinned=k;applyFlyout();if(k==='search')$('#menu-search').focus();}};
for(const n of [btn,pel]){n.addEventListener('mouseenter',()=>{clearTimeout(leaveTimer);hover=k;applyFlyout();});n.addEventListener('mouseleave',()=>{clearTimeout(leaveTimer);leaveTimer=setTimeout(()=>{if(hover===k)hover=null;applyFlyout();},250);});}
pel.addEventListener('focusout',()=>setTimeout(applyFlyout,0));}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&side.classList.contains('flyout')){const k=current();closeFlyout();panels[k]?.btn.focus();}});
document.addEventListener('click',e=>{if(pinned&&!side.contains(e.target))closeFlyout();});
$('#panel-state').addEventListener('change',e=>{const s=e.target.dataset.filter;if(!s)return;if(s==='all')filters.clear();else filters.has(s)?filters.delete(s):filters.add(s);render();});
init();
