import {readFile,access} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {validateGuide,validateProject,pageCandidates} from '../model.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>readFile(path.join(root,p),'utf8');
const guide=JSON.parse(await read('data/guide.json')),project=JSON.parse(await read('data/project.json'));
validateGuide(guide);validateProject(project,guide);
const ids=new Set(guide.categories.flatMap(c=>c.items.map(i=>i.id)));
const seedGuide=JSON.parse(await read('seed/guide.json')),seedProject=JSON.parse(await read('seed/project.json'));
try{validateGuide(seedGuide);validateProject(seedProject,seedGuide);for(const [id,e]of Object.entries(seedProject.sections))if(e.status!=='P'||e.page||e.owner||e.notes||e.exclusionReason||e.tasks.length||Object.values(e.review).some(Boolean))throw Error(`The seed must start empty and Pending: ${id}`);}catch(e){throw Error(`seed/: ${e.message}`);}
const exists=p=>access(path.join(root,p)).then(()=>true,()=>false);
const items=new Map(guide.categories.flatMap(c=>c.items.map(i=>[i.id,i])));
const htmls=['index.html'],dcPages=[];for(const [id,s]of Object.entries(project.sections)){const cands=pageCandidates(items.get(id),s);if(cands[0].startsWith('https://'))continue;const present=[];for(const f of cands)if(await exists(f))present.push(f);if(present.length>1)throw Error(`${id} has two pages: ${present.join(' and ')}`);if(!present.length){if(s.page)throw Error(`The page for ${id} does not exist: ${s.page}`);if(s.status==='I'||s.status==='R')throw Error(`${id} is ${s.status} and has no page at ${cands.join(' or ')}`);continue;}const file=present[0],content=await read(file);if(!content.includes(`name="ds-section-id" content="${id}"`))throw Error(`Identity meta missing: ${file}`);htmls.push(file);if(file.endsWith('.dc.html'))dcPages.push(file);}
const tableLike=/^(table|thead|tbody|tfoot|tr|colgroup|select|optgroup)$/,voids=new Set(['meta','link','br','hr','img','input','col','source','area','base','embed','track','wbr']);
function templateOutsideTables(html){const src=html.replace(/<!--[\s\S]*?-->/g,'').replace(/<(script|style)[\s\S]*?<\/\1>/gi,'');const stack=[];for(const m of src.matchAll(/<(\/?)([a-zA-Z][\w:-]*)[^>]*?(\/?)>/g)){const tag=m[2].toLowerCase();if(m[1]){const i=stack.lastIndexOf(tag);if(i>=0)stack.length=i;continue;}if(tag.startsWith('sc-')&&tableLike.test(stack.at(-1)||''))return `<${tag}> inside <${stack.at(-1)}>`;if(!m[3]&&!voids.has(tag))stack.push(tag);}return null;}
const runtime=['assets/_runtime/react.production.min.js','assets/_runtime/react-dom.production.min.js'],supports=new Map();
for(const file of dcPages){const html=await read(file),dir=path.dirname(file),srcs=[...html.matchAll(/<script[^>]*\ssrc="([^"]+)"/g)].map(m=>m[1]);const resolved=srcs.map(s=>/^https?:/.test(s)?s:path.posix.normalize(path.posix.join(dir,s)));const sup=resolved.indexOf(`${dir}/support.js`);if(sup<0)throw Error(`${file} does not link support.js`);for(const r of runtime)if(!(resolved.indexOf(r)>=0&&resolved.indexOf(r)<sup))throw Error(`${file} must load ${r} before support.js`);if(resolved.some(s=>/^https?:/.test(s)))throw Error(`${file} links external scripts`);if(!new RegExp(`<html[^>]*\\slang="${project.language}"`,'i').test(html))throw Error(`${file} must declare lang="${project.language}" on <html>`);for(const [,img]of html.matchAll(/["'](\.{1,2}\/[^"'\s{}]+\.(?:png|jpe?g|webp|gif|svg))["']/gi)){const target=path.resolve(root,dir,img);if(!target.startsWith(root+path.sep))throw Error(`Image outside the repo in ${file}: ${img}`);if(!await exists(path.relative(root,target)))throw Error(`${file} cites an image that does not exist: ${img}`);}const misplaced=templateOutsideTables(html);if(misplaced)throw Error(`${file}: ${misplaced}. The browser moves it out of the table and the container cannot recover it. Use elements with role="row"/"cell"`);const bytes=await readFile(path.join(root,dir,'support.js'));supports.set(dir,bytes);}
for(const [dir,bytes]of supports){const src=bytes.toString('utf8');for(const [name,file]of [['REACT','react.production.min.js'],['REACT_DOM','react-dom.production.min.js']]){const sri=src.match(new RegExp(`var ${name}_SRI = "(sha384-[^"]+)"`))?.[1];if(!sri)throw Error(`${dir}/support.js does not declare ${name}_SRI`);const own='sha384-'+createHash('sha384').update(await readFile(path.join(root,'assets/_runtime',file))).digest('base64');if(own!==sri)throw Error(`assets/_runtime/${file} does not match the version ${dir}/support.js expects. Update the vendored runtime (see assets/_runtime/README.md)`);}}
if(new Set([...supports.values()].map(b=>b.toString('base64'))).size>1)throw Error('The support.js copies are not identical: '+[...supports.keys()].join(', '));
for(const f of ['styles.css','app.js','model.js','scripts/init.mjs','seed/guide.json','seed/project.json','CLAUDE.md','README.md','docs/handoff.md','docs/claude-code.md','docs/claude-design.md'])await access(path.join(root,f));
for(const file of htmls){const html=await read(file);for(const [,href]of html.matchAll(/(?:href|src)="([^"]+)"/g)){if(/^(?:https?:|#|data:)/.test(href)||href.includes('{{'))continue;const target=path.resolve(root,path.dirname(file),href.split(/[?#]/)[0]);if(!target.startsWith(root+path.sep)&&target!==root)throw Error(`Reference outside the repo: ${href}`);await access(target);}}
console.log(`OK: ${guide.categories.length} categories, ${ids.size} subsections and ${htmls.length} linked pages checked.`);
