import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {validateProject,safePage,progressOf,pageCandidates} from '../model.js';
const guide=JSON.parse(await readFile(new URL('../data/guide.json',import.meta.url))),base=JSON.parse(await readFile(new URL('../data/project.json',import.meta.url)));const copy=()=>structuredClone(base),id=guide.categories[0].items[0].id;
test('Plantilla completa y pendiente',()=>{assert.equal(validateProject(base,guide),true);assert.equal(progressOf(base).percent,0);});
test('No aplica queda fuera del avance; todo N no divide por cero',()=>{const p=copy();for(const s of Object.values(p.sections)){s.status='N';s.exclusionReason='Fuera de alcance';}assert.equal(progressOf(p).percent,null);const s=p.sections[id];s.status='R';s.review={by:'Revisor',date:'2026-10-08',evidence:'Pruebas registradas'};assert.equal(progressOf(p).percent,100);validateProject(p,guide);});
test('Rechaza importaciones incompletas o estados desconocidos',()=>{const p=copy();delete p.sections[id];assert.throws(()=>validateProject(p,guide));const q=copy();q.sections[id].status='A';assert.throws(()=>validateProject(q,guide));});
test('Ready y N requieren evidencia explícita',()=>{for(const state of ['R','N']){const p=copy();p.sections[id].status=state;assert.throws(()=>validateProject(p,guide));}});
test('URLs y rutas no pueden ejecutar código o salir del repo',()=>{for(const s of ['javascript:alert(1)','data:text/html,test','../index.html','sections/../../index.html','https://user:password@example.com','file:///tmp/test.html','http://example.com'])assert.equal(safePage(s),false,s);for(const s of ['sections/visuales/color.html','sections/visuales/color.dc.html','https://example.com/design'])assert.equal(safePage(s),true,s);});
test('Rechaza versiones divergentes e IDs sustituidos',()=>{const p=copy();p.guideVersion='2';assert.throws(()=>validateProject(p,guide));const q=copy();q.sections.fake=q.sections[id];delete q.sections[id];assert.throws(()=>validateProject(q,guide));});
test('Sin page, la página es la ruta sugerida en sus dos variantes; con page, solo esa',()=>{const item=guide.categories[0].items[0],s=copy().sections[id];assert.deepEqual(pageCandidates(item,s),[item.suggestedPath,item.suggestedPath.replace(/\.html$/,'.dc.html')]);s.page='https://example.com/design';assert.deepEqual(pageCandidates(item,s),['https://example.com/design']);});
